""" add question_snapshot to test_answers """
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '88945e7ea258'
down_revision = '2b37baa6ab8d'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('question_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('test_answers', 'answer',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('test_answers', 'answered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_answers', 'answered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_answers', 'answer',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('test_answers', 'question_snapshot')
    # ### end Alembic commands ###
