""" add test_score to candidate_categories """
from alembic import op
import sqlalchemy as sa

revision = '8f70f2f704de'
down_revision = '88945e7ea258'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_categories', sa.Column('test_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_categories', 'test_score')
    # ### end Alembic commands ###
